export const GET_ERRORS = 'GET_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';

//USER ACTIONS
export const USER_REGISTER = 'USER_REGISTER';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';
export const USER_REGISTER_CLEANUP = 'USER_REGISTER_CLEANUP';

export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';
export const USER_LOGIN_CLEANUP = 'USER_LOGIN_CLEANUP';

export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS';
export const USER_LOGOUT_FAIL = 'USER_LOGOUT_FAIL';
export const USER_LOGOUT_CLEANUP = 'USER_LOGOUT_CLEANUP';

export const USER_FORGOT_PASSWORD = 'USER_FORGOT_PASSWORD';
export const USER_FORGOT_PASSWORD_SUCCESS = 'USER_FORGOT_PASSWORD_SUCCESS';
export const USER_FORGOT_PASSWORD_FAIL = 'USER_FORGOT_PASSWORD_FAIL';
export const USER_FORGOT_PASSWORD_CLEANUP = 'USER_FORGOT_PASSWORD_CLEANUP';

export const SET_CURRENT_USER_USER = 'SET_CURRENT_USER_USER';

export const USER_RESET_FORGOT_PASSWORD = 'USER_RESET_FORGOT_PASSWORD';
export const USER_RESET_PASSWORD = 'USER_RESET_PASSWORD';
export const GET_USER_DATA = 'GET_USER_DATA';
// requests
export const USER_CREATE_REQUEST = 'USER_CREATE_REQUEST';
export const USER_GET_REQUESTS = 'USER_GET_REQUESTS';
// docs
export const USER_UPLOAD_DOC = 'USER_UPLOAD_DOC';
export const USER_GET_DOCUMENT_SENT_BY_ADMIN = 'USER_GET_DOCUMENT_SENT_BY_ADMIN';
export const USER_GET_DOCUMENT_SENT_BY_USER = 'USER_GET_DOCUMENT_SENT_BY_USER';
// appointment
export const USER_BOOK_APPOINTMENT = 'USER_BOOK_APPOINTMENT';
export const USER_GET_APPOINTMENTS = 'USER_GET_APPOINTMENTS';

//ADMIN ACTIONS
export const ADMIN_REGISTER = 'ADMIN_REGISTER';
export const ADMIN_REGISTER_SUCCESS = 'ADMIN_REGISTER_SUCCESS';
export const ADMIN_REGISTER_FAIL = 'ADMIN_REGISTER_FAIL';
export const ADMIN_REGISTER_CLEANUP = 'ADMIN_REGISTER_CLEANUP';

export const ADMIN_LOGIN = 'ADMIN_LOGIN';
export const ADMIN_LOGIN_SUCCESS = 'ADMIN_LOGIN_SUCCESS';
export const ADMIN_LOGIN_FAIL = 'ADMIN_LOGIN_FAIL';
export const ADMIN_LOGIN_CLEANUP = 'ADMIN_LOGIN_CLEANUP';

export const ADMIN_LOGOUT = 'ADMIN_LOGOUT';
export const ADMIN_LOGOUT_SUCCESS = 'ADMIN_LOGOUT_SUCCESS';
export const ADMIN_LOGOUT_FAIL = 'ADMIN_LOGOUT_FAIL';
export const ADMIN_LOGOUT_CLEANUP = 'ADMIN_LOGOUT_CLEANUP';

export const ADMIN_FORGOT_PASSWORD = 'ADMIN_FORGOT_PASSWORD';
export const ADMIN_FORGOT_PASSWORD_SUCCESS = 'ADMIN_FORGOT_PASSWORD_SUCCESS';
export const ADMIN_FORGOT_PASSWORD_FAIL = 'ADMIN_FORGOT_PASSWORD_FAIL';
export const ADMIN_FORGOT_PASSWORD_CLEANUP = 'ADMIN_FORGOT_PASSWORD_CLEANUP';

export const SET_CURRENT_ADMIN_USER = 'SET_CURRENT_ADMIN_USER';

export const ADMIN_RESET_FORGOT_PASSWORD = 'ADMIN_RESET_FORGOT_PASSWORD';
export const ADMIN_RESET_PASSWORD = 'ADMIN_RESET_PASSWORD';
export const GET_ADMIN_DATA = 'GET_ADMIN_DATA';

// documents
export const ADMIN_UPLOAD_DOC = 'ADMIN_UPLOAD_DOC';
export const ADMIN_GET_ALL_DOCUMENTS = 'ADMIN_GET_ALL_DOCUMENTS';
export const ADMIN_GET_DOCUMENTS_SENT = 'ADMIN_GET_DOCUMENTS_SENT';
export const ADMIN_GET_DOCUMENTS_RECEIVED = 'ADMIN_GET_DOCUMENTS_RECEIVED';


// requests 
export const ADMIN_GET_ALL_REQUESTS = 'ADMIN_GET_ALL_REQUESTS';

// get clients under admin 
export const ADMIN_GET_CLIENTS = 'ADMIN_GET_CLIENTS';

// appointments 
export const ADMIN_GET_APPOINTMENTS = 'ADMIN_GET_APPOINTMENTS';
export const ADMIN_CONFRIM_APPOINTMENT = 'ADMIN_CONFRIM_APPOINTMENT';

// superadmin-client actions 
export const ADMIN_GET_CLIENT = 'ADMIN_GET_CLIENT';
export const ADMIN_GET_CLIENT_SUCCESS = 'ADMIN_GET_CLIENT_SUCCESS';
export const ADMIN_GET_CLIENT_FAIL = 'ADMIN_GET_CLIENT_FAIL';
export const ADMIN_GET_CLIENT_CLEANUP = 'ADMIN_GET_CLIENT_CLEANUP';
export const ADMIN_GET_CLIENT_DETAILS = 'ADMIN_GET_CLIENT_DETAILS';
export const ADMIN_GET_CLIENT_DETAILS_SUCCESS = 'ADMIN_GET_CLIENT_DETAILS_SUCCESS';
export const ADMIN_GET_CLIENT_DETAILS_FAIL = 'ADMIN_GET_CLIENT_DETAILS_FAIL';
export const ADMIN_GET_CLIENT_DETAILS_CLEANUP = 'ADMIN_GET_CLIENT_DETAILS_CLEANUP';
export const ADMIN_UPDATE_CLIENT_SUBSRCIPTION = 'ADMIN_UPDATE_CLIENT_SUBSCRIPTION';

// superadmin get all admins 
export const GET_ALL_ADMINS = 'GET_ALL_ADMINS';
// superadmin add user to admin
export const ADD_CLIENT_TO_ADMIN = 'ADD_CLIENT_TO_ADMIN';